### ISSUE TITLE
::cond:: support

### ISSUE THREAD

**Issue by Gama11** [influrium/vscode-templo#1]
First off, thanks for making this, makes working with the mtt files in dox a bit more bearable. :)

It seems `::cond::` isn't really supported yet?

![](https://i.imgur.com/CAHfD7A.png)

https://github.com/HaxeFoundation/dox/blob/master/themes/default/templates/package_description.mtt

**Comment by ConstNW** [comment]
You are welcome, thanks for yours report )

I'll rework extension and will fix this

**Comment by ConstNW** [comment]
now you get your update)

**Comment by Gama11** [comment]
Wow, that was fast. 👍
